// packages/ui/src/components/typography/index.tsx
import * as React from 'react'

import type { TypographyVariants } from '@yuki/ui/components/typography/variants'
import { typographyVariants } from '@yuki/ui/components/typography/variants'
import { cn } from '@yuki/ui/utils'

export interface TypographyProps
  extends Omit<React.HTMLAttributes<HTMLParagraphElement>, 'color'>,
    TypographyVariants {}

const Typography = React.forwardRef<HTMLButtonElement, TypographyProps>(
  ({ className, level = 'p', color, ...props }, ref) => {
    const Comp = level as React.ElementType

    return (
      <Comp
        className={cn(typographyVariants({ level, color, className }))}
        ref={ref}
        {...props}
      />
    )
  },
)
Typography.displayName = 'Typography'

export { Typography, typographyVariants }

// packages/ui/src/components/typography/typography.vue
<script setup lang="ts">
import type { PrimitiveProps } from 'radix-vue'
import type { HTMLAttributes } from 'vue'
import { Primitive } from 'radix-vue'

import { cn } from '@yuki/ui/utils'

import type { TypographyVariants } from './variants'
import { typographyVariants } from './variants'

interface Props extends PrimitiveProps {
  level?: TypographyVariants['level']
  color?: TypographyVariants['color']
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<Props>(), {
  level: 'p',
  color: 'primary',
  class: '',
})
</script>

<template>
  <Primitive
    :as="level as any"
    :as-child="asChild"
    :class="cn(typographyVariants({ level, color }), props.class)"
  >
    <slot />
  </Primitive>
</template>
