// apps/dashboard/src/routes/not-found.vue
<template>
  <main class="flex min-h-[90dvh] items-center justify-center">
    <h1
      class="m-0 mr-5 inline-block border-r p-0 pr-6 align-top text-2xl leading-12 font-medium"
    >
      404
    </h1>
    <div class="inline-block">
      <h2 class="m-0 text-sm leading-12 font-normal">
        This page could not be found.
      </h2>
    </div>
  </main>
</template>

// apps/web/app/not-found.tsx
export default function NotFoundPage() {
  return (
    <main className="flex min-h-dvh flex-col items-center justify-center">
      <div>
        <h1 className="mr-5 inline-block border-r pr-6 align-top text-2xl leading-12 font-medium">
          404
        </h1>
        <div className="inline-block">
          <p className="text-sm leading-12">This page could not be found.</p>
        </div>
      </div>
    </main>
  )
}
