// apps/dashboard/src/pages/not-found.vue
<template>
  <main class="container flex min-h-[90dvh] flex-col items-center justify-center">
    <div class="space-y-6 text-center">
      <Typography level="h1">404</Typography>
      <Typography level="h2" class="border-none">Page Not Found</Typography>
      <Typography>
        The page you're looking for doesn't exist or has been moved.
      </Typography>
    </div>
  </main>
</template>

<script setup lang="ts">
import { Typography } from '@yuki/ui/vue/typography'
</script>

// apps/web/app/not-found.tsx
export default function NotFoundPage() {
  return (
    <main className="flex min-h-dvh flex-col items-center justify-center">
      <div>
        <h1 className="mr-5 inline-block border-r pr-6 align-top text-2xl leading-12 font-medium">
          404
        </h1>
        <div className="inline-block">
          <p className="text-sm leading-12">This page could not be found.</p>
        </div>
      </div>
    </main>
  )
}
