// packages/ui/src/components/vue/avatar/avatar.vue
<script setup lang="ts">
import { AvatarRoot } from 'radix-vue'

import { cn } from '@yuki/ui/utils'

const defaultStyle = 'relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full'
</script>

<template>
  <AvatarRoot :class="cn(defaultStyle, $attrs.class ?? '')">
    <slot />
  </AvatarRoot>
</template>

// packages/ui/src/components/avatar.tsx
'use client'

import * as React from 'react'
import * as AvatarPrimitive from '@radix-ui/react-avatar'

import { cn } from '@yuki/ui/utils'

function Avatar({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Root>) {
  return (
    <AvatarPrimitive.Root
      data-slot="avatar"
      className={cn(
        'relative flex size-8 shrink-0 overflow-hidden rounded-full',
        className,
      )}
      {...props}
    />
  )
}

function AvatarImage({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Image>) {
  return (
    <AvatarPrimitive.Image
      data-slot="avatar-image"
      className={cn('aspect-square size-full', className)}
      {...props}
    />
  )
}

function AvatarFallback({
  className,
  ...props
}: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
  return (
    <AvatarPrimitive.Fallback
      data-slot="avatar-fallback"
      className={cn(
        'bg-muted flex size-full items-center justify-center rounded-full',
        className,
      )}
      {...props}
    />
  )
}

export { Avatar, AvatarImage, AvatarFallback }
