// packages/ui/src/components/toast/toaster.vue
<script setup lang="ts">
import { isVNode } from 'vue'

import { useToast } from '@yuki/ui/hooks/use-toast.vue'

import {
  Toast,
  ToastClose,
  ToastDescription,
  ToastProvider,
  ToastTitle,
  ToastViewport,
} from './index.vue'

const { toasts } = useToast()
</script>

<template>
  <ToastProvider>
    <Toast v-for="toast in toasts" :key="toast.id" v-bind="toast">
      <CircleCheckIcon v-if="toast.variant === 'success'" size="{20}" />
      <CircleAlertIcon v-if="toast.variant === 'warning'" size="{20}" />
      <InfoIcon v-if="toast.variant === 'info'" size="{20}" />
      <TriangleAlertIcon v-if="toast.variant === 'error'" size="{20}" />

      <div class="grid grow gap-1">
        <ToastTitle v-if="toast.title">
          {{ toast.title }}
        </ToastTitle>
        <template v-if="toast.description">
          <ToastDescription v-if="isVNode(toast.description)">
            <component :is="toast.description" />
          </ToastDescription>
          <ToastDescription v-else>
            {{ toast.description }}
          </ToastDescription>
        </template>
        <ToastClose />
      </div>
      <component :is="toast.action" />
    </Toast>
    <ToastViewport />
  </ToastProvider>
</template>

// packages/ui/src/components/toaster.tsx
'use client'

import {
  CircleAlertIcon,
  CircleCheckIcon,
  InfoIcon,
  TriangleAlertIcon,
} from 'lucide-react'

import {
  Toast,
  ToastClose,
  ToastDescription,
  ToastProvider,
  ToastTitle,
  ToastViewport,
} from '@yuki/ui/components/toast'
import { useToast } from '@yuki/ui/hooks/use-toast'

export function Toaster() {
  const { toasts } = useToast()

  return (
    <ToastProvider>
      {toasts.map(({ id, title, description, action, ...props }) => (
        <Toast key={id} {...props} className="mt-1">
          {props.variant === 'success' && <CircleCheckIcon size={20} />}
          {props.variant === 'warning' && <CircleAlertIcon size={20} />}
          {props.variant === 'info' && <InfoIcon size={20} />}
          {props.variant === 'error' && <TriangleAlertIcon size={20} />}

          <div className="grid grow gap-1">
            {title && <ToastTitle>{title}</ToastTitle>}
            {description && <ToastDescription>{description}</ToastDescription>}
          </div>
          {action}
          <ToastClose />
        </Toast>
      ))}
      <ToastViewport />
    </ToastProvider>
  )
}
