// packages/ui/src/components/badge/badge.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'

import { cn } from '@yuki/ui/utils'

import type { BadgeVariants } from './variants'
import { badgeVariants } from './variants'

interface Props {
  variant?: BadgeVariants['variant']
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'NEW',
  class: '',
})
</script>

<template>
  <span :class="cn(badgeVariants({ variant, class: props.class }))">
    <slot />
  </span>
</template>

// packages/ui/src/components/badge/index.tsx
import * as React from 'react'

import { cn } from '@yuki/ui/utils'

import type { BadgeVariants } from './variants'
import { badgeVariants } from './variants'

const Badge = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & BadgeVariants
>(({ variant, className, ...props }, ref) => (
  <span ref={ref} className={cn(badgeVariants({ variant, className }))} {...props} />
))
Badge.displayName = 'Badge'

export { Badge }
