// apps/dashboard/src/routes/auth/sign-in.vue
<script setup lang="ts">
import { ref } from 'vue'

import {
  Button,
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
  Input,
} from '@yuki/ui/vue'

import { useSession } from '@/hooks/use-session'

const { signIn, isSigningIn } = useSession()

const formData = ref({
  email: '',
  password: '',
})

const handleSubmit = () => {
  signIn(formData.value)
}
</script>

<template>
  <main class="container grid min-h-[90dvh] place-items-center">
    <Card as="form" class="w-full max-w-xl" @submit.prevent="handleSubmit">
      <CardHeader>
        <CardTitle>Sign In</CardTitle>
        <CardDescription>Sign in to your account</CardDescription>
      </CardHeader>

      <CardContent class="space-y-4">
        <Input v-model="formData.email" placeholder="Email" />
        <Input v-model="formData.password" placeholder="Password" type="password" />

        <p>
          Don't have an account?
          <RouterLink to="/auth/sign-up" class="hover:underline">
            Register now
          </RouterLink>
        </p>
      </CardContent>

      <CardFooter>
        <Button type="submit" class="w-full" :disabled="isSigningIn">
          Login
        </Button>
      </CardFooter>
    </Card>
  </main>
</template>

// apps/dashboard/app/(auth)/sign-in/page.tsx
import Link from 'next/link'

import { Button } from '@yuki/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@yuki/ui/card'
import { DiscordIcon } from '@yuki/ui/icons'

import { LoginForm } from '@/app/(auth)/_components/login-form'
import { seo } from '@/lib/seo'

const Page: React.FC = () => (
  <Card className="w-screen max-w-screen-md border-background md:border-border">
    <CardHeader>
      <CardTitle className="text-2xl">Login</CardTitle>
      <CardDescription>Enter your email below to login to your account</CardDescription>
    </CardHeader>

    <CardContent>
      <LoginForm />

      <Button variant="outline" className="mt-4 w-full" asChild>
        <Link href="/api/auth/discord">
          <DiscordIcon /> Login with Discord
        </Link>
      </Button>

      <div className="mt-4 text-center text-sm">
        Don&apos;t have an account?{' '}
        <Link href="/sign-up" className="underline">
          Sign up
        </Link>
      </div>
    </CardContent>
  </Card>
)

export default Page

export const metadata = seo({
  title: 'Login',
  url: '/sign-in',
})
