// apps/dashboard/src/components/header.vue
<script setup lang="ts">
import { useColorMode } from '@vueuse/core'

import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  Button,
  MoonIcon,
  Skeleton,
  SunIcon,
} from '@yuki/ui/vue'

import { useSession } from '@/hooks/use-session'
import { getAppUrl } from '@/lib/utils'

const { session, isLoading } = useSession()
const mode = useColorMode()

const logoUrl = `${getAppUrl()}/assets/logo.svg`

const navLinks = [
  { label: 'Categories', href: '/categories' },
  { label: 'Products', href: '/products' },
  { label: 'Orders', href: '/orders' },
  { label: 'Customers', href: '/customers' },
]
</script>

<template>
  <header
    class="bg-background/70 sticky inset-0 z-50 border-b py-4 shadow-md backdrop-blur-xl backdrop-saturate-150"
  >
    <div class="container flex items-center justify-between gap-4">
      <RouterLink to="/" class="flex items-center gap-2 text-2xl font-bold">
        <img class="size-9 dark:invert" :src="logoUrl" alt="Logo" />
        <span class="sr-only not-sr-only">Dashboard</span>
      </RouterLink>

      <nav class="hidden grow gap-2 md:flex">
        <RouterLink
          v-for="link in navLinks"
          :key="link.href"
          :to="link.href"
          class="text-muted-foreground hover:text-foreground"
          :class="{ 'text-primary': $route.path.startsWith(link.href) }"
        >
          {{ link.label }}
        </RouterLink>
      </nav>

      <Skeleton v-if="isLoading" class="size-9 rounded-full" />
      <Button v-else-if="!session?.user"> Login </Button>
      <Avatar v-else class="ring-ring size-9 hover:ring-2">
        <AvatarFallback>{session.user.name[0]}</AvatarFallback>
        <AvatarImage :src="session.user.image" :alt="session.user.name" />
      </Avatar>

      <Button
        variant="ghost"
        size="icon"
        @click="mode = mode === 'dark' ? 'light' : 'dark'"
      >
        <SunIcon v-if="mode === 'light'" />
        <MoonIcon v-else />
      </Button>
    </div>
  </header>
</template>

// apps/dashboard/app/components/header/index.tsx
import { Link, NavLink } from 'react-router'

import { cn } from '@yuki/ui/utils'

import { env } from '@/env'
import { User } from './user'

export const Header: React.FC = () => (
  <header className="bg-background/70 sticky inset-0 z-50 flex h-20 items-center border-b shadow-md backdrop-blur-xl backdrop-saturate-150">
    <div className="container flex items-center justify-between gap-4">
      <Link to="/" className="flex items-center gap-2">
        <img
          src={`${env.VITE_WEB_URL}/assets/logo.svg`}
          alt="Logo"
          className="size-9 dark:invert"
        />
        <span className="sr-only text-2xl font-bold md:not-sr-only">
          Dashboard
        </span>
      </Link>

      <nav className="ml-6 flex items-center space-x-6">
        {navItems.map((item) => (
          <NavLink
            key={item.href}
            to={item.href}
            className={({ isActive }) =>
              cn(
                'hover:text-primary flex items-center space-x-2 text-sm font-medium transition-colors',
                isActive ? 'text-foreground' : 'text-muted-foreground',
              )
            }
          >
            {item.label}
          </NavLink>
        ))}
      </nav>

      <User />
    </div>
  </header>
)

const navItems = [
  {
    label: 'Products',
    href: '/products',
  },
  {
    label: 'Categories',
    href: '/categories',
  },
  {
    label: 'Orders',
    href: '/orders',
  },
  {
    label: 'Customers',
    href: '/customers',
  },
]
