// apps/dashboard/app/(dashboard)/customers/page.tsx
import type { NextPage } from 'next'
import Link from 'next/link'

import { Button } from '@yuki/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@yuki/ui/table'

import { api } from '@/lib/trpc/server'

const Page: NextPage = async () => {
  const customers = await api.user.getAll({})

  return (
    <Table>
      <TableHeader>
        <TableRow>
          {headers.map((header, index) => (
            <TableHead key={index}>{header}</TableHead>
          ))}
        </TableRow>
      </TableHeader>

      <TableBody>
        {customers.length === 0 && (
          <TableRow className="text-muted-foreground">
            <TableCell align="center" colSpan={headers.length}>
              No customers found
            </TableCell>
          </TableRow>
        )}

        {customers.map((customer) => (
          <TableRow key={customer.id}>
            <TableCell>{customer.id}</TableCell>
            <TableCell>{customer.name}</TableCell>
            <TableCell>{customer.role}</TableCell>
            <TableCell>{customer.createdAt.toDateString()}</TableCell>
            <TableCell className="space-x-2">
              <Button size="sm" asChild>
                <Link href={`/customers/${customer.id}`}>Edit</Link>
              </Button>
              <Button variant="destructive" size="sm" asChild>
                <Link href={`/customers/${customer.id}/delete`}>Delete</Link>
              </Button>
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  )
}

export default Page

const headers = ['ID', 'Name', 'Role', 'Joined at', 'Actions']

// apps/dashboard/src/routes/customers.vue
<script setup lang="ts">
import { ref } from 'vue'

import { Button } from '@yuki/ui/vue/button'
import { Loader2Icon } from '@yuki/ui/vue/icons'

import { useCustomers } from '@/hooks/use-customers'

const headers = ref(['Name', 'Role', 'Number of Orders', 'Actions'])
const { customers, isLoading } = useCustomers({})
</script>
<template>
  <main class="container py-4">
    <h1 class="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
      Customers
    </h1>

    <div v-if="isLoading" class="flex h-64 items-center justify-center">
      <Loader2Icon class="h-8 w-8" />
    </div>

    <table v-else class="mt-4 w-full">
      <thead>
        <tr class="even:bg-muted m-0 border-t p-0">
          <th
            v-for="header in headers"
            :key="header"
            class="border px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right"
          >
            {{ header }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="customer in customers"
          :key="customer.id"
          class="even:bg-muted/40 m-0 border-t p-0"
        >
          <td
            class="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right"
          >
            {{ customer.name }}
          </td>
          <td
            class="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right"
          >
            {{ customer.role }}
          </td>
          <td
            class="border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right"
          >
            {{ customer.numberOfOrders }}
          </td>
          <td
            class="grid grid-cols-2 gap-2 border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right"
          >
            <Button size="sm"> Edit </Button>
            <Button variant="destructive" size="sm"> Delete </Button>
          </td>
        </tr>
      </tbody>
    </table>
  </main>
</template>
