// packages/ui/src/components/textarea/textarea.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { useVModel } from '@vueuse/core'

import { cn } from '@yuki/ui/utils'

import { textareaVariants } from './variants'

const props = defineProps<{
  class?: HTMLAttributes['class']
  defaultValue?: string | number
  modelValue?: string | number
}>()

const emits = defineEmits<(e: 'update:modelValue', payload: string | number) => void>()

const modelValue = useVModel(props, 'modelValue', emits, {
  passive: true,
  defaultValue: props.defaultValue,
})
</script>

<template>
  <textarea v-model="modelValue" :class="cn(textareaVariants({ class: props.class }))" />
</template>

// packages/ui/src/components/textarea/index.tsx
import * as React from 'react'

import { cn } from '@yuki/ui/utils'

import type { TextareaVariants } from './variants'
import { textareaVariants } from './variants'

const Textarea: React.FC<React.ComponentProps<'textarea'> & TextareaVariants> = ({
  className,
  ...props
}) => <textarea className={cn(textareaVariants({ className }))} {...props} />
Textarea.displayName = 'Textarea'

export { Textarea }
