// packages/ui/src/components/input/index.tsx
import * as React from 'react'

import { cn } from '@yuki/ui/utils'

import type { InputVariants } from './variants'
import { inputVariants } from './variants'

const Input: React.FC<React.ComponentProps<'input'> & InputVariants> = ({
  className,
  ...props
}) => <input className={cn(inputVariants({ className }))} {...props} />
Input.displayName = 'Input'

export { Input }

// packages/ui/src/components/input/input.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { useVModel } from '@vueuse/core'

import { cn } from '@yuki/ui/utils'

import { inputVariants } from './variants'

const props = defineProps<{
  defaultValue?: string | number
  modelValue?: string | number
  class?: HTMLAttributes['class']
}>()

const emits = defineEmits<(e: 'update:modelValue', payload: string | number) => void>()

const modelValue = useVModel(props, 'modelValue', emits, {
  passive: true,
  defaultValue: props.defaultValue,
})
</script>

<template>
  <input v-model="modelValue" :class="cn(inputVariants({ class: props.class }))" />
</template>
